import type { Metadata } from "next";
import { Open_Sans } from "next/font/google"; 
import "./globals.css";
import Navbar from "@/components/Navbar";

const openSans = Open_Sans({
  subsets: ["latin"], 
  variable: "--font-open-sans", 
  weight: ["300", "400", "600", "700", "800"], 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${openSans.variable} antialiased`}>
         
         <Navbar />
        {/* Render children */}
        {children}
      </body>
    </html>
  );
}
